#!/usr/bin/env bash
# script to install and configure HAproxy on load balancer server

set -e  # Exit on error

# Update and upgrade packages
apt-get update
apt-get -y upgrade

# Install HAProxy
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y install haproxy

# Define variables
DOMAIN_NAME='munyasi.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'

# HAProxy configuration
HAPROXY_LB_CONFIG="backend $DOMAIN_NAME-backend
    balance roundrobin
    server 20639-web-01 3.227.217.150:80 check
    server 20639-web-02 3.95.27.202:80 check

frontend $DOMAIN_NAME-frontend
    bind *:80
    mode http
    default_backend $DOMAIN_NAME-backend"

# Check if INIT_FILE exists
if [ ! -f "$INIT_FILE" ]; then
    touch "$INIT_FILE"
fi

# Check if CONFIG_FILE exists
if [ ! -f "$CONFIG_FILE" ]; then
    touch "$CONFIG_FILE"
fi

# Enable HAProxy in INIT_FILE
if ! grep -q '^ENABLED=[01]$' "$INIT_FILE"; then
    echo 'ENABLED=1' >> "$INIT_FILE"
fi

# Update or add HAProxy configuration in CONFIG_FILE
sed -i "/#--$DOMAIN_NAME-params-begin--/,/#--$DOMAIN_NAME-params-end--/d" "$CONFIG_FILE"
echo -e "$HAPROXY_LB_CONFIG" >> "$CONFIG_FILE"

# Restart or start HAProxy service
if systemctl is-active --quiet haproxy; then
    systemctl restart haproxy
else
    systemctl start haproxy
fi

echo "HAProxy installation and configuration completed."
